name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Create version artifact
        run: |
          echo ${{ matrix.python-version }} > version.txt
          echo "::set-output name=version::$(cat version.txt)"
        id: version
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-versions
          path: version.txt
